---
title: "Assignment 6"
author: "Benjamin Moran \n c3076448 (University of Newcastle)"
date: 'Date Generated: `r Sys.Date()`'
# bibliography: AssX.bib
output:
  pdf_document: default
  html_document:
    df_print: tibble
    fig_caption: yes
subtitle: STAT904 Statistical Consulting
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#### Plagiarism Statement 
No part of this Assignment has been copied from anyone else, and I have not lent any part of it to anyone else.

# Question 1

Identify 2 modern sources that consider how to select statistical analysis procedures. Provide a one-page summary what you learnt from them.

# Question 2

The number of fatal accidents on a stretch of road over a 10 year period has been:
$$
0~2~1~0~3~1~2~0~1~0
$$
After lowering the speed limit to 80kms an hour the number of fatal accidents in the following five years is:

$$
0~0~0~1~0
$$
Users of the road are lobbying for the speed limit to be increased back to the original 100kms an hour. They say that the drop in the number of fatalities after the lowering of the speed limit is due to chance. 

The consulting company you work for is contracted to assess the effectiveness of the reduction in the speed limit and particularly whether the position of the road users is valid statistically.

## a) 

List 6 questions you would ask about this project.

## b) 

Undertake whatever analyses and calculations you think are useful. Write a report of no more than three pages. Clearly state your conclusions about the road users assertion that the observed effect of the lowering of the speed limit is due to chance.

# References
