---
title: "Assignment 5"
author: "Benjamin Moran \n c3076448 (University of Newcastle)"
date: 'Date Generated: `r Sys.Date()`'
bibliography: AssX.bib
output:
  pdf_document: default
  html_document:
    df_print: tibble
    fig_caption: yes
subtitle: STAT904 Statistical Consulting
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#### Plagiarism Statement 
No part of this Assignment has been copied from anyone else, and I have not lent any part of it to anyone else.

# Question 1

A client wants to know what sample size to use. After some questioning you determine that the main objective of the national study is to estimate the proportion of people who are obese. The client seems to have difficulty in expressing the reliability required.

## a) Construct a table giving the margin of error for different sample sizes for estimating the relevant proportion for a realistic range of assumptions about the proportion.

## b) After further discussion it becomes clear that there is a requirement to produce estimates for each of the six states and compare the proportion of people who are obese between the six states. Construct further tables to help your discussions with the client of the sample size required.

## c) The client ask you to write as short report containing the tables and some commentary on what they mean to take to a steering committee meeting. Produce such a report. Be sure to make clear the assumptions you have made the sampling procedure to be used.

# Question 2

A client wants to conduct a survey to analyse the change in the proportion of people who eat at least 2 serves of vegetables a day before and after an advertising campaign that promotes healthy eating. Assume independent samples at each occasion and that the current proportion is approximately 30%.

## a) Suppose you are testing a null hypothesis H0 versus H1. Define the power of a statistical test. Briefly explain how this definition applies to this survey.

## b) What is the target population for the survey?

## c) What size sample is needed on each occasion to estimate the change with a margin of error of 2 percentage point? Show your calculations.

## d) What size sample is needed on each occasion to have an 80% power of detecting a true change of 2 percentage point, using a test with size of 5%? How does the sample size change if a 90% power is needed? Show your calculations.

## e) Comment on the results of (c) and (d).

# References
