---
title: "Assignment 3"
author: "Benjamin Moran \n c3076448 (University of Newcastle)"
date: 'Date Generated: `r Sys.Date()`'
# bibliography: AssX.bib
output:
  pdf_document: default
  html_document:
    df_print: tibble
    fig_caption: yes
subtitle: STAT904 Statistical Consulting
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#### Plagiarism Statement 
No part of this Assignment has been copied from anyone else, and I have not lent any part of it to anyone else.

# Question 1. 

There are several professional societies that a statistician can belong to and which provide useful information. Check the web sites of the Statistical Society of Australia, the Royal Statistical Society and the American Statistical Association.

## (a) For each of these web sites write a one-page summary of what potentially valuable information or resources are available.

## (b) What are the requirements for you to become accredited as a Graduate Statistician (G. Stat.) by the Statistical Society of Australia? What additional requirements are there to become and Accredited Statistician?

The requirements for accreditation as a Graduate Statisitician are strictly educational. From the ...

> __5.3.1 Education requirement__
Holders of the qualification of Graduate Statistician shall meet at least the following educational requirements, provided no more than eight years has elapsed since the award of the degree or equivalent on which the application is based: 
>
1.  A pass degree from an Australian university, or equivalent qualification.
2.  A minimum of 25% of a year's study in Statistics in total at second year level, and a minimum of 50% of a year's study in Statistics at third year level. 
3.  A four year Honours degree in Statistics, or the applicant has achieved a minimum average grade of 65% (that is, a credit average or equivalent) in their Statistical major at third year level or in the Statistics postgraduate coursework in the degree that forms the basis of their application.
4.  Units involving statistical inference, data analysis, statistical communication skills and the use of a statistical package. 
5.  Several units covering material from the following list: probability and distribution theory, linear models, design of experiments, sampling methods, multivariate analysis, analysis of categorical data, time series, survival analysis, statistical consulting, statistical graphics, databases. 

### Accredited Statistician

In addition to the educational requirements for becoming a _G. Stat_, becoming an _Accredited Statistician_ requires experience. [^#]

> __5.4.2 Experience__ The applicant needs to demonstrate an appropriate level of competence in the  application of statistical methods. Here, application refers to the use of  statistical methods in connection with analysis and/or modelling and /or  reporting of work in which the handling of real -world  data is an important part.  Theoretical work is not sufficient of itself ; the emphasis is on application to  data, not on research into the theory of statistics . This should not be taken to  exclude  work in which the primary focus is theoretical, as long as there is a  part that can be regarded as application. 
>
a. Where the educational requirement is met through 1 of  5.4.1,  a further  six (6) years of practical experience is required. 
b. Where the educational requirement is met through 1  of 5.4.1  and the  applicant has a  first or second class Honours degree including an  honours year with at least 50% statistical content , a further four (4)  years  only  of practical experience is required. 
c. Where the educational requirement is met  through  2 of 5.4.1,  at least  ten (10) years of practical experience is required. 
d. For at least three (3)  years of the qualification period, applicants must  have taken  responsibility for the statistical content of their work. 
e. Practical experience is not limited to paid employment; it may occur in  a range of forms of practical activity. The Accreditation Committee will  consider any practical experience which the applicant believes to be  relevant. 
f. In considering the evidence for experience, the Accreditation  Committee will take into account the length of experience and the level  of expertise involved, and may exercise discretion in considering what  constitutes  evidence of experience and expertise. 
g. Applicants who h ave undertaken study for higher or other  postgraduate degrees in Statistics may count some of their years of  study for these degrees, up to a maximum of two- thirds of the study,  towards the experience qualification, provided it fits within the practical   


## (c) Briefly summarise any information that the web sites contain about ethics and standards for statisticians including protecting individuals’ confidentiality.


# Question 2. 

Time series data are common in many situations.

## (a) What does it mean if a time series is described as stationary?

There are two types of stationary: _strictly stationary_ and _weakly stationary_. For definitions, we'll be relying on _Time Series Analysis and Its Applications With R Examples_ by _R. Shumway_ and _D. Stoffer_ [@TSA2011 pp. 22-3].

### Strictly Stationary

_Shumway_ and _Stoffer_ define __strictly stationary__ as follows [-@TSA2011 p. 22]: 

> __Definition 1.6__: A strictly stationary time series is one for which the probabilistic behavior of every collection of values
$$
\{x_{t_1}, x_{t_2}, \hdots, x_{t_k}\}
$$
is identical to that of the time shifted set
$$
\{ x_{t_{1+h}}, x_{t_{2+h}}, \hdots, x_{t_{k+h}} \}
$$
That is,
$$
P\{ x_{t_1} \leq c_1, \hdots, x_{t_k} \leq c_k \} = P\{x_{t_{1+h}} \leq c_1, \hdots, x_{t_{k+h}} \leq c_k \}
$$
for all $k = 1, 2, \hdots,$ all time points $t_1, t_2, \hdots, t_k,$ all numbers $c_1, c2,\hdots, c_k,$ and all time shifts $h = 0,\pm 1, \pm 2, \hdots.$

### Weakly Stationary
 
_Shumway_ and _Stoffer_ define __weakly stationary__ as follows [-@TSA2011 p. 23]: 
 
> __Definition 1.7__:  A weakly stationary time series, $x_t$, is a finite variance process such that:

> \quad (i) the mean value function, $\mu_t$ is constant and does not depend on time $t$, and 

> \quad (ii) the autocovariance function, $\gamma(s, t)$ depends on $s$ and $t$ only through their difference $\mid s - t \mid$.

## (b) A client approaches you to advise on an analysis of their monthly sales data. They run a national chain of plant nursery shops.

### 1) Write a short note explaining what seasonality and seasonal adjustment are and why they might be important for the client.

### 2) Construct some simple hypothetical data about sales of plant nursery shops that illustrates the idea of seasonality.

### 3) Suggest two initial steps that the client could do after the first consultation with you.

# Question 3.

A political lobby group approaches you and wishes to make the case that the price of health and education are increasing faster than other items. Write a short report on how the consumer price index (CPI) is compiled by the Australian Bureau of Statistics (ABS) and whether the case the lobby group is making is reasonable.


# References


[^#]: This is a footnote
